practice_todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_app.urls", namespace="todo"))
]

todo_app/urls.py
from django.urls import path

from todo_app.views import HomePageTaskView, TagListView, TaskCreateView, TaskUpdateView, task_status, TagCreateView, \
    TagUpdateView, TagDeleteView, TaskDeleteView

urlpatterns = [
    path("", HomePageTaskView.as_view(), name="homepage"),
    path("tags/", TagListView.as_view(), name="tags"),
    path("tags/create", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/update",TagUpdateView.as_view(), name="tag_update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag_delete"),
    path("task/create/", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"),
    path("task/toggle_status/<int:pk>/", task_status, name="task_status"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),

]

app_name = "todo"

todo_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.content



todo_app/forms.py
from django import forms

from todo_app.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('content', 'deadline', 'tags')
        widgets = {
            "deadline": forms.DateInput(attrs={'type': 'date'}),
            "tags": forms.CheckboxSelectMultiple(),
        }

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name',)

todo_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from todo_app.forms import TaskForm, TagForm
from todo_app.models import Task, Tag


class HomePageTaskView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags").all().order_by("is_done", "-created_at")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('todo:homepage')


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo:tags")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("todo:tags")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tags")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:homepage")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:homepage")


class TagListView(generic.ListView):
    model = Tag


def task_status(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect(reverse("todo:homepage"))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>todo</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">


</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>

    <div class="col-sm-10">
      {% block content %}
      {% endblock %}
    
    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="list-group">
  <li class="list-group-item"><a href="{% url 'todo:homepage' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tags' %}">Tags</a></li>
</ul>

templates/todo_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

templates/todo_app/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h2>Are you sure that you want to delete this tag?</h2>
  <form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, im sure">
  </form>
{% endblock %}

templates/todo_app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form method="post" action="">
  {{ form|crispy }}
  {% csrf_token %}
  <input type="submit" value="submit">
  </form>
{% endblock %}

templates/todo_app/tag_list.html
{% extends "base.html" %}
{% block content %}
   <a href="{% url "todo:tag_create" %}" class="btn btn-primary link-to-page">
      Add
    </a>
  <br><br>
  {% if tag_list %}
  <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a class="btn btn-secondary" style="text-decoration: none;" href="{% url "todo:tag_update" pk=tag.id %}">update</a></td>
        <td><a class="btn btn-secondary" style="text-decoration: none;" href="{% url "todo:tag_delete" pk=tag.id %}">delete</a></li></td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
  <h3 style="color: saddlebrown"> No tags</h3>
  {% endif %}
{% endblock %}

templates/todo_app/tags.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

templates/todo_app/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h2>Are you sure that you want to delete this task?</h2>
  <form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes, im sure">
  </form>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form method="post" action="">
  {{ form|crispy }}
  {% csrf_token %}
  <input type="submit" value="submit">
  </form>
{% endblock %}

templates/todo_app/task_list.html
{% extends "base.html" %}
{% block content %}
  <h1>
    TODO list
    <a href="{% url "todo:task_create" %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  <br><br>

  {% if task_list %}
  {% for task in task_list %}

    <h5>{{ task.content }} {% if task.is_done %}<a style="color: green">Done</a> {% else %}
      <a style="color: red"> Not done</a>{% endif %}</h5>

    <a href="{% url "todo:task_status" pk=task.id %}"
       class="btn btn-{% if task.is_done %}secondary{% else %}success{% endif %} link-to-page">
      {% if task.is_done %}
        Undo
      {% else %}
        Complete
      {% endif %}
    </a>
    <p>
      Created at: {{ task.created_at }} {% if task.deadline %} 
      <strong style="color: saddlebrown"> {{ task.deadline }}</strong>{% endif %}
    </p>
    <p>
      Tags:
      {% for tag in task.tags.all %}
        <a style="color: dimgray"> {{ tag.name }}</a>
      {% endfor %}
    <a style="text-decoration: none;" href="{% url "todo:task_update" pk=task.id %}"> update</a>
    <a style="text-decoration: none;" href="{% url "todo:task_delete" pk=task.id %}"> delete</a>
    </p>
    

    <hr>
  {% endfor %}
  {% else %}
  <h3 style="color: saddlebrown"> no tasks </h3>
  {% endif %}
{% endblock %}